{%- if values.adminAccessEntryName1 %}
---
apiVersion: infrastructure.skylab.com/v1alpha1
kind: XEKSAccessEntries
metadata:
  name: ${{ values.name }}-admin-access
  namespace: crossplane-${{ values.name }}
  labels:
    environment: ${{ values.environment }}
    cluster-type: ${{ values.clusterType }}
    cluster-name: ${{ values.name }}
    managed-by: backstage-template
    template: eks-cluster-crossplane
    component: admin-access
  annotations:
    backstage.io/managed-by-location: url:https://github.com/SkylarHoughtonGithub/skylab-backstage-configs/blob/main/${{ values.environment }}/${{ values.clusterType }}/${{ values.name }}/infra/crossplane/catalog-info.yaml
    template.backstage.io/created-by: ${{ values.name }}-eks-cluster-template
spec:
  clusterName: ${{ values.name }}-${{ values.environment }}
  region: ${{ values.region }}
  awsAccountId: "${{ values.awsAccountId | default('635314249418') }}"
  adminPrincipal:
    name: ${{ values.adminAccessEntryName1 }}
    type: ${{ values.adminAccessEntryType1 | default('role') }}
{%- endif %}

# ReadOnly Access Entry Composition (Optional)
{%- if values.readOnlyAccessEntryName1 %}
---
apiVersion: infrastructure.skylab.com/v1alpha1
kind: XEKSAccessEntries
metadata:
  name: ${{ values.name }}-readonly-access
  namespace: crossplane-${{ values.name }}
  labels:
    environment: ${{ values.environment }}
    cluster-type: ${{ values.clusterType }}
    cluster-name: ${{ values.name }}
    managed-by: backstage-template
    template: eks-cluster-crossplane
    component: readonly-access
  annotations:
    backstage.io/managed-by-location: url:https://github.com/SkylarHoughtonGithub/skylab-backstage-configs/blob/main/${{ values.environment }}/${{ values.clusterType }}/${{ values.name }}/infra/crossplane/catalog-info.yaml
    template.backstage.io/created-by: ${{ values.name }}-eks-cluster-template
spec:
  clusterName: ${{ values.name }}-${{ values.environment }}
  region: ${{ values.region }}
  awsAccountId: "${{ values.awsAccountId | default('635314249418') }}"
  readonlyPrincipal:
    name: ${{ values.readOnlyAccessEntryName1 }}
    type: ${{ values.readOnlyAccessEntryType1 | default('role') }}
{%- endif %}