---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: eks-cluster-crossplane
  title: Kubernetes Cluster with Crossplane
  description: Create a new Kubernetes cluster using Crossplane
  tags:
    - kubernetes
    - crossplane
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Cluster Configuration
      required:
        - name
        - environment
        - clusterType
      properties:
        name:
          title: Cluster Name
          type: string
          pattern: '^[a-z0-9-]+$'
          description: Name for your cluster (lowercase, numbers, hyphens only)
        environment:
          title: Environment
          type: string
          enum:
            - dev
            - staging
            - prod
          description: Target environment for the cluster
        clusterType:
          title: Cluster Type
          type: string
          enum:
            - eks
            - gke
            - aks
          description: Kubernetes platform type
        clusterVariant:
          title: Cluster Variant
          type: string
          enum:
            - standard
            - gpu-enabled
            - cost-optimized
            - high-availability
          default: standard
          description: Type of cluster configuration to deploy

    - title: Optional Settings
      properties:
        region:
          title: AWS Region
          type: string
          default: us-east-2
        nodeCount:
          title: Node Count
          type: integer
          default: 1
          minimum: 1
          maximum: 10
        nodeSize:
          title: Node Instance Type
          type: string
          default: t3.medium
          enum:
            - t3.medium
    - title: Admin Access Configuration
      description: Configure IAM principals that will have admin access to the EKS cluster
      properties:
        adminAccessEntryName1:
          title: Primary Admin Principal Name
          type: string
          description: "Name of IAM user or role (e.g., 'MyAdminRole' or 'john.doe')"
          default: chicken
        adminAccessEntryType1:
          title: Primary Admin Principal Type
          type: string
          enum:
            - role
            - user
          default: user
        adminAccessEntryName2:
          title: Secondary Admin Principal Name (Optional)
          type: string
          description: "Name of additional IAM user or role for admin access"
        adminAccessEntryType2:
          title: Secondary Admin Principal Type
          type: string
          enum:
            - role
            - user
          default: role
          
    - title: Read-Only Access Configuration
      description: Configure IAM principals that will have read-only access to the EKS cluster
      properties:
        readOnlyAccessEntryName1:
          title: Primary Read-Only Principal Name (Optional)
          type: string
          description: "Name of IAM user or role for read-only access"
        readOnlyAccessEntryType1:
          title: Primary Read-Only Principal Type
          type: string
          enum:
            - role
            - user
          default: role
        readOnlyAccessEntryName2:
          title: Secondary Read-Only Principal Name (Optional)
          type: string
          description: "Name of additional IAM user or role for read-only access"
        readOnlyAccessEntryType2:
          title: Secondary Read-Only Principal Type
          type: string
          enum:
            - role
            - user
          default: role

  steps:
    - id: fetch-cluster-template
      name: Fetch Cluster Template
      action: fetch:template
      input:
        url: ./templates/${{ parameters.clusterVariant }}
        values:
          name: ${{ parameters.name }}
          environment: ${{ parameters.environment }}
          clusterType: ${{ parameters.clusterType }}
          clusterVariant: ${{ parameters.clusterVariant }}
          region: ${{ parameters.region }}
          nodeCount: ${{ parameters.nodeCount }}
          nodeSize: ${{ parameters.nodeSize }}

    - id: publish-pr
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=SkylarHoughtonGithub&repo=skylab-backstage-configs
        branchName: add-${{ parameters.environment }}-${{ parameters.clusterType }}-${{ parameters.name }}-infra
        title: 'Add ${{ parameters.clusterVariant }} EKS cluster: ${{ parameters.name }}'
        description: |
          ## New EKS Cluster Infrastructure
          
          - **Cluster Name**: ${{ parameters.name }}
          - **Environment**: ${{ parameters.environment }}
          - **Cluster Type**: ${{ parameters.clusterType }}
          - **Variant**: ${{ parameters.clusterVariant }}
          - **Region**: ${{ parameters.region }}
          - **Node Count**: ${{ parameters.nodeCount }}
          - **Node Size**: ${{ parameters.nodeSize }}
          
          This PR adds new cluster infrastructure to `${{ parameters.environment }}/${{ parameters.clusterType }}/${{ parameters.name }}/infra/crossplane/`
          
          The cluster will be managed by Crossplane and deployed via ArgoCD ApplicationSet.
        targetPath: ${{ parameters.environment }}/${{ parameters.clusterType }}/${{ parameters.name }}/infra/crossplane

    - id: wait-for-merge
      name: Wait for PR to be merged
      action: debug:wait
      input:
        seconds: 15

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/SkylarHoughtonGithub/skylab-backstage-configs/blob/main/${{ parameters.environment }}/${{ parameters.clusterType }}/${{ parameters.name }}/infra/crossplane/catalog-info.yaml

    - id: completion-message
      name: Cluster Creation Complete
      action: debug:log
      input:
        message: |
          EKS Cluster Infrastructure Created!
          
          Pull Request: ${{ steps['publish-pr'].output.remoteUrl }}
          Cluster Path: ${{ parameters.environment }}/${{ parameters.clusterType }}/${{ parameters.name }}/infra/crossplane
          
          Next Steps:
          1. Review and merge the pull request
          2. Verify the cluster appears in your Backstage catalog
          3. Monitor ArgoCD for sync status
          4. Check Crossplane for cluster provisioning status

  output:
    links:
      - title: Pull Request
        url: ${{ steps['publish-pr'].output.remoteUrl }}
        icon: github
      - title: Repository
        url: https://github.com/SkylarHoughtonGithub/skylab-backstage-configs
        icon: catalog
      - title: ArgoCD 
        url: https://argocd.skylarhoughtongithub.local
        icon: dashboard
    text:
      - title: Cluster Path
        content: ${{ parameters.environment }}/${{ parameters.clusterType }}/${{ parameters.name }}/infra/crossplane
      - title: Branch Name
        content: add-${{ parameters.environment }}-${{ parameters.clusterType }}-${{ parameters.name }}-infra
      - title: Expected Application Name
        content: cluster-name-crossplane-infra-${{ parameters.environment }}