---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ${{ values.name }}-crossplane-cluster

resources:
  - manifests/composition.yaml

labels:
- includeSelectors: true
  pairs:
    environment: ${{ values.environment }}
    cluster-type: ${{ values.clusterType }}
    cluster-name: ${{ values.name }}
    managed-by: crossplane
    layer: infra
    component: crossplane

namespace: crossplane-system

patches:
  - target:
      kind: Composition
      name: ${{ values.name }}-eks-cluster
    patch: |-
      - op: add
        path: /metadata/labels/backstage.io~1managed-by
        value: template